#[cfg(not(target_arch = "wasm32"))]
pub mod accounts;
pub mod client;
#[cfg(not(target_arch = "wasm32"))]
pub mod legacy;
#[cfg(not(target_arch = "wasm32"))]
pub mod persist;
pub mod protocol;
#[cfg(not(target_arch = "wasm32"))]
pub mod server;
#[cfg(not(target_arch = "wasm32"))]
pub mod telemetry;
#[cfg(target_arch = "wasm32")]
pub mod ws;
#[cfg(not(target_arch = "wasm32"))]
pub mod world_manager;
